services:
  - type: web
    name: ipl-victory-predictor
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run main.py --server.address 0.0.0.0 --server.port $PORT
    autoDeploy: true
